name: Build
on: [pull_request,push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Permission
        run: chmod +x gradlew
      #- name: Build the app
      #  run: ./gradlew build
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
            token: ${{secrets.github_token}}
      - name: Build debug apk
        run: ./gradlew clean assembleDebug
      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.3
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: betwork_1.0.0.apk
          asset_content_type: application/zip